/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import java.sql.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Year;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.entity.Filijala;
import model.entity.Mesto;
import model.entity.Nalog;
import model.entity.Obrazac;
import model.entity.PoreskiObveznik;

/**
 *
 * @author HP
 */
public class AddNalogForma extends javax.swing.JFrame {

    String operation;
    NalogForma parent;
    Nalog n;

    /**
     * Creates new form NalogForma
     */
    public AddNalogForma(NalogForma parent, boolean modal, Nalog n, String operation) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.parent = parent;
        this.n = n;
        this.operation = operation;
        
        fillCmbFilijala();
        fillCmbObrazac();
        fillCmbMesto();
        fillCmbPO();
        
        if (operation.equals("UPDATE")) {
            adjustFields(n);
        } else {
            cmbMesto.setEnabled(false);
            try {
                fillForm(n);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Greska prilikom ucitavanja broja naloga!", "Greska", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDUrucenja = new javax.swing.JTextField();
        txtDIzdavanja = new javax.swing.JTextField();
        txtVUrucenja = new javax.swing.JTextField();
        cmbFilijala = new javax.swing.JComboBox();
        cmbObrazac = new javax.swing.JComboBox();
        cmbMesto = new javax.swing.JComboBox();
        cmbPO = new javax.swing.JComboBox();
        btnAdd = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtBroj = new javax.swing.JTextField();
        txtGodina = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Obrazac:");

        jLabel2.setText("Filijala:");

        jLabel3.setText("DatumUrucenja:");

        jLabel4.setText("DatumIzdavanja:");

        jLabel5.setText("VremeUrucenja:");

        jLabel6.setText("Mesto:");

        jLabel7.setText("Poreski obveznik:");

        cmbFilijala.setEditable(true);

        cmbObrazac.setEditable(true);

        cmbMesto.setEditable(true);

        cmbPO.setEditable(true);

        btnAdd.setText("Unesi nalog");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel8.setText("Broj:");

        jLabel9.setText("Godina:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(21, 21, 21)
                        .addComponent(txtVUrucenja))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(63, 63, 63)
                        .addComponent(cmbObrazac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(22, 22, 22)
                        .addComponent(txtDUrucenja))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDIzdavanja, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(cmbFilijala, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbPO, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbMesto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(71, 71, 71)
                        .addComponent(txtGodina, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(87, 87, 87)
                        .addComponent(txtBroj, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbFilijala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbObrazac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDIzdavanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDUrucenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtVUrucenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAdd)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            if (this.operation.equals("INSERT")) {
                this.insert();
            } else if (this.operation.equals("UPDATE")) {
                this.update();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
            adjustFields(n);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNalogForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNalogForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNalogForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNalogForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new AddNalogForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox cmbFilijala;
    private javax.swing.JComboBox cmbMesto;
    private javax.swing.JComboBox cmbObrazac;
    private javax.swing.JComboBox cmbPO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBroj;
    private javax.swing.JTextField txtDIzdavanja;
    private javax.swing.JTextField txtDUrucenja;
    private javax.swing.JTextField txtGodina;
    private javax.swing.JTextField txtVUrucenja;
    // End of variables declaration//GEN-END:variables

    private void fillForm(Nalog n) throws Exception {
        int godina = Integer.parseInt(String.valueOf(Year.now()));
        txtGodina.setText(String.valueOf(godina));
        int broj = Controller.getInstance().getNextBroj(new Nalog());
        txtBroj.setText(String.valueOf(++broj));
        txtGodina.setEnabled(false);
        txtBroj.setEnabled(false);
    }

    private void adjustFields(Nalog n) {
        txtGodina.setText(String.valueOf(n.getGodina()));
        txtBroj.setText(String.valueOf(n.getBroj()));
        txtGodina.setEnabled(false);
        txtBroj.setEnabled(false);
        cmbFilijala.setSelectedItem(n.getFilijala());
        cmbObrazac.setSelectedItem(n.getObrazac());
        txtDIzdavanja.setText(String.valueOf(n.getDatumIzdavanja()));
        txtDUrucenja.setText(String.valueOf(n.getDatumUrucenja()));
        txtVUrucenja.setText(String.valueOf(n.getVremeUrucenja()));
        cmbMesto.setSelectedItem(n.getMesto());
        cmbPO.setSelectedItem(n.getPoreskiObveznik());
        this.btnAdd.setText("Izmeni nalog");
    }

    private void fillCmbFilijala() {
        try {
            cmbFilijala.removeAllItems();
            List<Filijala> filijale = Controller.getInstance().getFilijalaList();
            for (Filijala filijala : filijale) {
                cmbFilijala.addItem(filijala);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska prilikom ucitavanja filijala!", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void fillCmbObrazac() {
        try {
            cmbObrazac.removeAllItems();
            List<Obrazac> obrasci = Controller.getInstance().getObrazacList();
            for (Obrazac obrazac : obrasci) {
                cmbObrazac.addItem(obrazac);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska prilikom ucitavanja obrazaca!", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void fillCmbMesto() {
        try {
            cmbMesto.removeAllItems();
            List<Mesto> mesta = Controller.getInstance().getMestaList();
            for (Mesto mesto : mesta) {
                cmbMesto.addItem(mesto);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska prilikom ucitavanja mesta!", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void fillCmbPO() {
        try {
            cmbPO.removeAllItems();
            List<PoreskiObveznik> po = Controller.getInstance().getPoreskiObveznikList();
            for (PoreskiObveznik poreskiObveznik : po) {
                cmbPO.addItem(poreskiObveznik);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska prilikom ucitavanja poreskih obveznika!", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void insert() throws Exception {
        if (txtDIzdavanja.getText().isEmpty() || txtDUrucenja.getText().isEmpty() || txtVUrucenja.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate popuniti sva polja!");
            return;
        }
        
        int broj = Integer.parseInt(txtBroj.getText());
        int godina = Integer.parseInt(txtGodina.getText());
        Filijala filijala = (Filijala) cmbFilijala.getSelectedItem();
        Obrazac obrazac = (Obrazac) cmbObrazac.getSelectedItem();
        String dIzdavanja = txtDIzdavanja.getText();
        String dUrucenja = txtDUrucenja.getText();
        String vUrucenja = txtVUrucenja.getText();
        Mesto mesto = (Mesto) cmbMesto.getSelectedItem();
        PoreskiObveznik po = (PoreskiObveznik) cmbPO.getSelectedItem();

        Date datumIzdavanja = new Date();
        Date datumUrucenja = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        try {
            datumIzdavanja = sdf.parse(dIzdavanja);
            datumUrucenja = sdf.parse(dUrucenja);
        } catch (ParseException ex) {
            Logger.getLogger(AddNalogForma.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Datum mora biti u odgovarajucem formatu!");
            return;
        }
        
        Timestamp vremeUrucenja = Timestamp.valueOf(vUrucenja);
        
        Nalog n = new Nalog(broj, godina, filijala, obrazac, datumIzdavanja, datumUrucenja, vremeUrucenja, mesto, po);
        
        Controller.getInstance().insert2(n);
        JOptionPane.showMessageDialog(this, "Uspesno dodat novi nalog!", "Uspesno", JOptionPane.INFORMATION_MESSAGE);
        parent.refreshTable();
        this.setVisible(false);
        dispose();
    }

    private void update() throws Exception {
        if (txtDIzdavanja.getText().isEmpty() || txtDUrucenja.getText().isEmpty() || txtVUrucenja.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate popuniti sva polja!");
            return;
        }
        
        int broj = Integer.parseInt(txtBroj.getText());
        int godina = Integer.parseInt(txtGodina.getText());
        Filijala filijala = (Filijala) cmbFilijala.getSelectedItem();
        Obrazac obrazac = (Obrazac) cmbObrazac.getSelectedItem();
        String dIzdavanja = txtDIzdavanja.getText();
        String dUrucenja = txtDUrucenja.getText();
        String vUrucenja = txtVUrucenja.getText();
        Mesto mesto = (Mesto) cmbMesto.getSelectedItem();
        PoreskiObveznik po = (PoreskiObveznik) cmbPO.getSelectedItem();

        Date datumIzdavanja = new Date();
        Date datumUrucenja = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        try {
            datumIzdavanja = sdf.parse(dIzdavanja);
            datumUrucenja = sdf.parse(dUrucenja);
        } catch (ParseException ex) {
            Logger.getLogger(AddNalogForma.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Datum mora biti u odgovarajucem formatu!");
            return;
        }
        
        Timestamp vremeUrucenja = Timestamp.valueOf(vUrucenja);
        
        Nalog nalog = new Nalog(broj, godina, filijala, obrazac, datumIzdavanja, datumUrucenja, vremeUrucenja, mesto, po);
        
        if(!mesto.equals(n.getMesto())){
            nalog.setMestoIzmena(true);
        }
        
        Controller.getInstance().update(nalog);
        JOptionPane.showMessageDialog(this, "Uspesno ste izmenili nalog!", "Uspesno", JOptionPane.INFORMATION_MESSAGE);
        parent.refreshTable();
        this.setVisible(false);
        dispose();
    }
}
